language: java
jdk:
- oraclejdk8
- oraclejdk11

cache:
  directories:
    - "$HOME/.m2"

install:
  - "mvn clean:clean resources:resources compiler:compile jar:jar shade:shade install:install"

script:
  - "mvn resources:testResources compiler:testCompile surefire:test"

deploy:
  -
    provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P j8"
    on:
      all_branches: true
      jdk: oraclejdk8
  -
    provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P j11"
    on:
      all_branches: true
      jdk: oraclejdk11