language: java
jdk:
  - oraclejdk8
install:
  - mvn clean:clean resources:resources compiler:compile jar:jar shade:shade install:install
script:
  - mvn resources:testResources compiler:testCompile surefire:test