jdk:
- oraclejdk8
- oraclejdk11

cache:
  directories:
  - $HOME/.m2

stages:
  - install
  - test
  - deploy

jobs:
  include:
    -
      stage: install
      jdk: oraclejdk8
      script: mvn clean:clean resources:resources compiler:compile jar:jar shade:shade install:install
    -
      stage: test
      script: mvn resources:testResources compiler:testCompile surefire:test
    -
      stage: deploy
      jdk: oraclejdk8
      script: mvn clean deploy -P j8
    -
      jdk: oraclejdk11
      script: mvn clean deploy -P j11