language: java

matrix:
  include:
    - jdk: oraclejdk8
      env: MVN_PROFILE=j8
    - jdk: oraclejdk11
      env: MVN_PROFILE=j11

cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn clean:clean resources:resources compiler:compile jar:jar shade:shade install:install -P $MAVEN_PROFILE

script:
  - mvn resources:testResources compiler:testCompile surefire:test -P $MAVEN_PROFILE

deploy:
  -
    provider: script
    script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P $MAVEN_PROFILE
    on:
      all_branches: true