language: java
jdk:
- oraclejdk8
- oraclejdk11

cache:
  directories:
  - $HOME/.m2

stages:
  - install
  - test
  - deploy

install:
  - mvn clean:clean resources:resources compiler:compile jar:jar shade:shade install:install

script:
  - mvn resources:testResources compiler:testCompile surefire:test

jobs:
  include:
    -
      stage: deploy
      if: env(TRAVIS_TEST_RESULT) = true
      jdk: oraclejdk8
      script: mvn clean deploy -P j8
    -
      if: env(TRAVIS_TEST_RESULT) = true
      jdk: oraclejdk11
      script: mvn clean deploy -P j11